import {useEffect, useState} from "react";
import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [addressInput, setAddressInput] = useState("");
  const [passport, setPassport] = useState({});

  const [verifier, setVerifier] = useState(undefined);

  useEffect(() => {
    const initVerifier = async () => {
      // Dynamically load @gitcoinco/passport-sdk-verifier
      const PassportVerifier = (await import("@gitcoinco/passport-sdk-verifier")).PassportVerifier;
      setVerifier(new PassportVerifier("https://ceramic.staging.dpopp.gitcoin.co"));
    };
    initVerifier().then(() => {
      console.log("Verifier inited :)");
    });
  }, []);

  const handleSubmit = (event) => {
    event.preventDefault();
    const cred = {
      "signature": "0x3079dbdf3e6750e4c6dfb150d43925635376d1fed33ea0b3a436de1d349cce2f0c40de7200e0536ffe54a9d353fc9a17216eef0f845c864f0c6bd96f07b133251b",
      "challenge": {
          "@context": [
              "https://www.w3.org/2018/credentials/v1"
          ],
          "type": [
              "VerifiableCredential"
          ],
          "credentialSubject": {
              "id": "did:pkh:eip155:1:0x7A67063c391F266D31eA6c9eC7C788c1323B7746",
              "provider": "challenge-GithubOrg",
              "address": "0x7A67063c391F266D31eA6c9eC7C788c1323B7746",
              "challenge": "I commit that this stamp is my unique and only GithubOrg verification for Passport.\n\nnonce: 01a0a5328afe04795046931fde0ebdee07f1d500bb738d3d5af97559b97a5bbd",
              "@context": [
                  {
                      "address": "https://schema.org/Text",
                      "challenge": "https://schema.org/Text",
                      "provider": "https://schema.org/Text"
                  }
              ]
          },
          "issuer": "did:key:z6Mkgtpm1B5PXZCZZJKADWP3dC6Lkew5hVbv9Q1h8SVAQk2M",
          "issuanceDate": "2022-08-01T17:30:54.499Z",
          "proof": {
              "type": "Ed25519Signature2018",
              "proofPurpose": "assertionMethod",
              "verificationMethod": "did:key:z6Mkgtpm1B5PXZCZZJKADWP3dC6Lkew5hVbv9Q1h8SVAQk2M#z6Mkgtpm1B5PXZCZZJKADWP3dC6Lkew5hVbv9Q1h8SVAQk2M",
              "created": "2022-08-01T17:30:54.500Z",
              "jws": "eyJhbGciOiJFZERTQSIsImNyaXQiOlsiYjY0Il0sImI2NCI6ZmFsc2V9..zG2gnqraw5bJu7TywY4xLpJLfkcifRxGDo4vh0DNVB1lhDmZKKMSaKM_GdIHDsiuw1EO_wzJmB9cWVgBbGhaDA"
          },
          "expirationDate": "2022-08-01T17:31:54.499Z"
      },
      "record": {
          "type": "GithubOrg",
          "version": "0.0.0",
          "org": "gitcoinco",
          "handle": "schultztimothy"
      },
      "credential": {
          "@context": [
              "https://www.w3.org/2018/credentials/v1"
          ],
          "type": [
              "VerifiableCredential"
          ],
          "credentialSubject": {
              "id": "did:pkh:eip155:1:0x7A67063c391F266D31eA6c9eC7C788c1323B7746",
              "@context": [
                  {
                      "hash": "https://schema.org/Text",
                      "provider": "https://schema.org/Text"
                  }
              ],
              "provider": "GithubOrg",
              "hash": "v0.0.0:Pqx+xqZbvZu0uNnmLexkHAGT9hkENyV+xrV1epvGZu4="
          },
          "issuer": "did:key:z6Mkgtpm1B5PXZCZZJKADWP3dC6Lkew5hVbv9Q1h8SVAQk2M",
          "issuanceDate": "2022-08-01T17:30:57.228Z",
          "proof": {
              "type": "Ed25519Signature2018",
              "proofPurpose": "assertionMethod",
              "verificationMethod": "did:key:z6Mkgtpm1B5PXZCZZJKADWP3dC6Lkew5hVbv9Q1h8SVAQk2M#z6Mkgtpm1B5PXZCZZJKADWP3dC6Lkew5hVbv9Q1h8SVAQk2M",
              "created": "2022-08-01T17:30:57.229Z",
              "jws": "eyJhbGciOiJFZERTQSIsImNyaXQiOlsiYjY0Il0sImI2NCI6ZmFsc2V9..NkV2nSA1N1eZoib7WdwH66OoY6JHSTQPY3cgL8pPA6lzNmpcfYB9l0PCc5cBslzw5cwUHpNAmnfuYDCfhDS9Ag"
          },
          "expirationDate": "2022-10-30T17:30:57.228Z"
      }
  }
    verifier.verifyCredential(cred.credential).then((result) => {
      console.log({ result })
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main className={styles.main}>
        <img src="GitcoinLogo.svg" alt="logo"/>
        <h1>Passport Verifier SDK</h1>
        <p>Enter Wallet Address to verify passport</p>
        <form>
          <input
            type="text"
            name="inputAddress"
            style={{padding: 12}}
            // @ts-ignore
            onChange={(e) => setAddressInput(e.target.value)}
            value={addressInput}
          />
          <button style={{padding: 12}} onClick={handleSubmit}>
            Enter
          </button>
        </form>
        {passport && (
          <div
            style={{
              padding: 10,
              marginTop: 10,
              fontSize: 14,
              textAlign: "left",
            }}
          >
            <h1 style={{textAlign: "center"}}>Passport Stamps</h1>
            {
              // @ts-ignore
              passport?.stamps?.length > 0 && (
                <div>
                  Stamps:{" "}
                  <ul>
                    {
                      // @ts-ignore
                      passport?.stamps?.map((item, index) => {
                        return (
                          <li key={index}>
                            {item.provider}: {item.verified ? "✅" : "❌"}
                          </li>
                        );
                      })
                    }
                  </ul>
                </div>
              )
            }
          </div>
        )}
      </main>
    </div>
    // <div className={styles.container}>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>
    //
    //   <main className={styles.main}>
    //     <h1 className={styles.title}>
    //       Welcome to <a href="https://nextjs.org">Next.js!</a>
    //     </h1>
    //
    //     <p className={styles.description}>
    //       Get started by editing{' '}
    //       <code className={styles.code}>pages/index.js</code>
    //     </p>
    //
    //     <div className={styles.grid}>
    //       <a href="https://nextjs.org/docs" className={styles.card}>
    //         <h2>Documentation &rarr;</h2>
    //         <p>Find in-depth information about Next.js features and API.</p>
    //       </a>
    //
    //       <a href="https://nextjs.org/learn" className={styles.card}>
    //         <h2>Learn &rarr;</h2>
    //         <p>Learn about Next.js in an interactive course with quizzes!</p>
    //       </a>
    //
    //       <a
    //         href="https://github.com/vercel/next.js/tree/canary/examples"
    //         className={styles.card}
    //       >
    //         <h2>Examples &rarr;</h2>
    //         <p>Discover and deploy boilerplate example Next.js projects.</p>
    //       </a>
    //
    //       <a
    //         href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //         className={styles.card}
    //       >
    //         <h2>Deploy &rarr;</h2>
    //         <p>
    //           Instantly deploy your Next.js site to a public URL with Vercel.
    //         </p>
    //       </a>
    //     </div>
    //   </main>
    //
    //   <footer className={styles.footer}>
    //     <a
    //       href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //       target="_blank"
    //       rel="noopener noreferrer"
    //     >
    //       Powered by{' '}
    //       <span className={styles.logo}>
    //         <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
    //       </span>
    //     </a>
    //   </footer>
    // </div>
  )
}
